name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    timeout-minutes: 60
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Use GPR
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: 'https://npm.pkg.github.com'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies
        run: yarn
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Ping NPM
        run: npm ping

      - name: Set Git User
        run: |
          git config --global user.email "rbolxcode@gmail.com"
          git config --global user.name "rbolxcode"

      - name: Set _auth
        run: |
          npm set _auth=$AUTH_TOKEN

      - name: Create Release Pull Request
        uses: changesets/action@v1
        id: changesets
        with:
          # this expects you to have a npm script called version that runs some logic and then calls `changeset release`.
          version: yarn version
          publish: yarn release
          setupGitUser: false
          title: '[ci] release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.ARTIFACTORY_PASSWORD }}
          NPM_TOKEN: ${{ secrets.ARTIFACTORY_PASSWORD }}